// Minimal country list with dial codes; extend as needed.
// Using ISO2 codes and international dialing prefixes
export interface PhoneCountry {
  name: string;
  iso2: string; // lowercase
  dial: string; // digits without +
}

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { name: "United States", iso2: "us", dial: "1" },
  { name: "Canada", iso2: "ca", dial: "1" },
  { name: "Mexico", iso2: "mx", dial: "52" },
  { name: "El Salvador", iso2: "sv", dial: "503" },
  { name: "Guatemala", iso2: "gt", dial: "502" },
  { name: "Honduras", iso2: "hn", dial: "504" },
  { name: "Nicaragua", iso2: "ni", dial: "505" },
  { name: "Costa Rica", iso2: "cr", dial: "506" },
  { name: "Panama", iso2: "pa", dial: "507" },
  { name: "Colombia", iso2: "co", dial: "57" },
  { name: "Peru", iso2: "pe", dial: "51" },
  { name: "Chile", iso2: "cl", dial: "56" },
  { name: "Argentina", iso2: "ar", dial: "54" },
  { name: "Brazil", iso2: "br", dial: "55" },
  { name: "Afghanistan", iso2: "af", dial: "93" },
  { name: "Albania", iso2: "al", dial: "355" },
  { name: "Algeria", iso2: "dz", dial: "213" },
  { name: "American Samoa", iso2: "as", dial: "1" },
  { name: "Andorra", iso2: "ad", dial: "376" },
  { name: "Angola", iso2: "ao", dial: "244" },
  { name: "Anguilla", iso2: "ai", dial: "1" },
  { name: "Antigua and Barbuda", iso2: "ag", dial: "1" },
  { name: "Armenia", iso2: "am", dial: "374" },
  { name: "Aruba", iso2: "aw", dial: "297" },
  { name: "Australia", iso2: "au", dial: "61" },
  { name: "Austria", iso2: "at", dial: "43" },
  { name: "Azerbaijan", iso2: "az", dial: "994" },
  { name: "Bahamas", iso2: "bs", dial: "1" },
  { name: "Bahrain", iso2: "bh", dial: "973" },
  { name: "Bangladesh", iso2: "bd", dial: "880" },
  { name: "Barbados", iso2: "bb", dial: "1" },
  { name: "Belgium", iso2: "be", dial: "32" },
  { name: "Belize", iso2: "bz", dial: "501" },
  { name: "Benin", iso2: "bj", dial: "229" },
  { name: "Bermuda", iso2: "bm", dial: "1" },
  { name: "Bolivia", iso2: "bo", dial: "591" },
  { name: "Bosnia and Herzegovina", iso2: "ba", dial: "387" },
  { name: "Botswana", iso2: "bw", dial: "267" },
  { name: "Bulgaria", iso2: "bg", dial: "359" },
  { name: "Cameroon", iso2: "cm", dial: "237" },
  { name: "Cayman Islands", iso2: "ky", dial: "1" },
  { name: "China", iso2: "cn", dial: "86" },
  { name: "Cuba", iso2: "cu", dial: "53" },
  { name: "Czechia", iso2: "cz", dial: "420" },
  { name: "Denmark", iso2: "dk", dial: "45" },
  { name: "Dominican Republic", iso2: "do", dial: "1" },
  { name: "Ecuador", iso2: "ec", dial: "593" },
  { name: "Egypt", iso2: "eg", dial: "20" },
  { name: "France", iso2: "fr", dial: "33" },
  { name: "Germany", iso2: "de", dial: "49" },
  { name: "Greece", iso2: "gr", dial: "30" },
  { name: "Haiti", iso2: "ht", dial: "509" },
  { name: "India", iso2: "in", dial: "91" },
  { name: "Ireland", iso2: "ie", dial: "353" },
  { name: "Israel", iso2: "il", dial: "972" },
  { name: "Italy", iso2: "it", dial: "39" },
  { name: "Jamaica", iso2: "jm", dial: "1" },
  { name: "Japan", iso2: "jp", dial: "81" },
  { name: "Luxembourg", iso2: "lu", dial: "352" },
  { name: "Netherlands", iso2: "nl", dial: "31" },
  { name: "New Zealand", iso2: "nz", dial: "64" },
  { name: "Norway", iso2: "no", dial: "47" },
  { name: "Paraguay", iso2: "py", dial: "595" },
  { name: "Poland", iso2: "pl", dial: "48" },
  { name: "Portugal", iso2: "pt", dial: "351" },
  { name: "Romania", iso2: "ro", dial: "40" },
  { name: "Russia", iso2: "ru", dial: "7" },
  { name: "Saudi Arabia", iso2: "sa", dial: "966" },
  { name: "South Africa", iso2: "za", dial: "27" },
  { name: "Spain", iso2: "es", dial: "34" },
  { name: "Sweden", iso2: "se", dial: "46" },
  { name: "Switzerland", iso2: "ch", dial: "41" },
  { name: "Turkey", iso2: "tr", dial: "90" },
  { name: "United Kingdom", iso2: "gb", dial: "44" },
  { name: "Uruguay", iso2: "uy", dial: "598" },
  { name: "Venezuela", iso2: "ve", dial: "58" },
];
